# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function generate shuffled DGE
#' @param n_genes number of genes
#' @param n_bcds number of barcodes
#' @param num_nonzeros number of non-zero umis
#' @param numis vector of umis
#' @param geneInd vector of gene index
#' @param barcodeInd index of barcoders
#' @param totalumi sum of umis
#' @return a list
#' @export
dgeShuffle <- function(n_genes, n_bcds, num_nonzeros, numis, geneInd, barcodeInd, totalumi) {
    .Call(`_SiftCell_dgeShuffle`, n_genes, n_bcds, num_nonzeros, numis, geneInd, barcodeInd, totalumi)
}

#' Rcpp function to get the gene profile of ambient droplets
#' @param m a sparse matrix of ambient drpolets
#' @param nrow the rows of m
#' @param ncol the cols of m
#' @export
getAmbientProp <- function(m, nrow, ncol) {
    .Call(`_SiftCell_getAmbientProp`, m, nrow, ncol)
}



#' Rcpp function to get the coefficieint of DMM
#' @param geneProfile matrix of gene profile for all cell types and soup
#' @param mtx a DGE matrix
#' @param ub_p a vector of upper bound for p
#' @param lb_p a vector of lower bound for p
#' @return a matrix with convergence and coefficients
runDMM <- function(geneProfile, mtx, ub_p, lb_p) {
    .Call(`_SiftCell_runDMM`, geneProfile, mtx, ub_p, lb_p)
}

