# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgeShuffle <- function(n_genes, n_bcds, num_nonzeros, numis, geneInd, barcodeInd, totalumi) {
    .Call('_SiftCell_dgeShuffle', PACKAGE = 'SiftCell', n_genes, n_bcds, num_nonzeros, numis, geneInd, barcodeInd, totalumi)
}

